export const CREATE_USERS_MANAGEMENT = 'createUsersManagement'
export const CREATE_USER_MANAGEMENT = 'createUserManagement'
export const CREATE_EXCEPTION_MANAGEMENT = 'createExceptionManagement'
export const CREATE_AUTH_MANAGEMENT = 'createAuthManagement'
export const SET_USERS_LIST = 'setUsersList'
export const SET_USER_DETAILS = 'setUserDetails'