export const CREATE_USERS_MANAGEMENT = 'createUsersManagement'
export const CREATE_EXCEPTION_MANAGEMENT = 'createExceptionManagement'
export const SET_USERS_LIST = 'setUsersList'
export const SET_USER_DETAILS = 'setUserDetails'
export const DELETE_USER = 'deleteUser'
export const CREATE_USER = 'createUser'
export const SET_SEARCHED_PHRASE = 'setSearchedPhrase'
export const SET_EXCEPTION = 'setException'