export const CREATE_USERS_MANAGEMENT = 'createUsersManagement'
export const SET_USERS_LIST = 'setUsersList'
export const DELETE_USER = 'deleteUser'
export const CREATE_USER = 'createUser'
export const SET_SEARCHED_PHRASE = 'setSearchedPhrase'